Support SAML SSO
oktadev/id-assertion-authz-node-example pull request #12
Opened 2024-04-08 19:18 UTC by sdesen

**SAML Implementation**
- Passport SAML for SSO to Idp for token exchange

**Folder restructure**
- Move auth server logic into lib folder
- move oidc and passport strategies into their own files

**Migrations**
- Relax constraints on users if they belong to more than 1 org

**Documentation**
- Instructions for how to run apps in SAML or OIDC mode

**Debug Console Updates**
- Cache ID in redis from auth server for debug console to use
- Frontend changes to display

![Screenshot 2024-05-13 at 5 22 53 PM](https://github.com/oktadev/id-assertion-authz-node-example/assets/160887862/41bf4f2f-ab29-4f0d-807d-eeb82474887d)
![Screenshot 2024-05-13 at 5 23 11 PM](https://github.com/oktadev/id-assertion-authz-node-example/assets/160887862/bcc165f4-493a-4b71-b5e2-7b4ab462ed99)

2024-05-01 21:13 UTC, neelav requested changes

2024-05-01 21:13 UTC, neelav commented on todo0/prisma/schema.prisma
> +  @@unique([email, orgId, externalId])
do we really need email in this index?  I would think orgId and externalId are sufficient.  Also the index should probably lead with orgId

2024-05-01 21:13 UTC, neelav commented on todo0/src/server/controllers/oidc.ts
> +        res.clearCookie('connect.sid', { path: '/' });
do we need to clear these additional cookies?  Aren't they owned by the auth server?

2024-05-01 21:13 UTC, neelav commented on wiki0/prisma/schema.prisma
> +  @@unique([email, orgId, externalId])
same comment as the todo server

2024-05-01 21:13 UTC, neelav commented on wiki0/prisma/schema.prisma
> +  // same prisma error as in in auth token schema
what error is this referring to?

2024-05-01 21:13 UTC, neelav commented on wiki0/src/client/components/home.tsx
> +          The IDP (i.e. Okta) redirects back to the Wiki0 auth server, providing an ID Assertion
screenshots of the new changes please

2024-05-01 21:13 UTC, neelav commented on wiki0/src/server/controllers/oidc.ts
> +        res.clearCookie('connect.sid', { path: '/' });
same question about cookie clearing

2024-05-01 22:40 UTC, neelav commented on todo0/src/server/controllers/oidc.ts
> +        res.clearCookie('connect.sid', { path: '/' });
yah it probably wont work in production since the domains are different

2024-05-01 22:42 UTC, neelav commented on wiki0/prisma/schema.prisma
> +  @@unique([email, orgId, externalId])
ah okay, that makes sense.  Can you add this comment in the code?

2024-05-01 22:42 UTC, neelav commented on wiki0/prisma/schema.prisma
> +  // same prisma error as in in auth token schema
ah that's right. Let's copy/paste the error here too

2024-05-16 21:56 UTC, kamronbatman commented on wiki0/src/server/controllers/authtoken.ts
> +      requestBody.subject_token = assertion || '';
```suggestion
      requestBody.subject_token = assertion ?? '';
```

2024-05-16 21:57 UTC, kamronbatman commented on authorization-server/utils/id-token-cache.js
> +    cache[makeCacheKey(subject, client_id)] || { subjectToken: undefined, tokenType: undefined }
```suggestion
    cache[makeCacheKey(subject, client_id)] ?? { subjectToken: undefined, tokenType: undefined }
```

2024-05-16 21:58 UTC, kamronbatman commented on authorization-server/utils/id-token-cache.js
> +    cache[makeCacheKey(subject, client_id)] || { subjectToken: undefined, tokenType: undefined }
Note: I would prefer `null` instead of `undefined` if we don't get issues with that.

2024-05-16 21:59 UTC, kamronbatman commented on authorization-server/utils/id-token-cache.js
> +    cache[makeCacheKey(subject, client_id)] || { subjectToken: undefined, tokenType: undefined }
Also maybe this would work?

```suggestion
    cache[makeCacheKey(subject, client_id)] ?? {}
```

2024-05-16 22:45 UTC, neelav reviewed
I find this PR too big to follow clearly.  It's mixing a few different things together: saml, debug console, redis, etc.  Any chance you could break up this PR?

2024-05-17 16:04 UTC, closed without merging