Sdesen docs
oktadev/id-assertion-authz-node-example pull request #26
Opened 2024-08-16 16:41 UTC by sdesen

2024-08-16 22:35 UTC, kamronbatman commented on README.md
> +> **Tip!**  Checkout the Debug Console in the App for detailed views of the requests!
```suggestion
> [!TIP]
> Checkout the Debug Console in the App for detailed views of the requests!
```

2024-08-16 22:35 UTC, kamronbatman commented on README.md
> +> **Tip!**  Checkout the Debug Console in the App for detailed views of the requests!
```suggestion
> [!TIP]
> Checkout the Debug Console in the App for detailed views of the requests!
```

2024-08-16 22:35 UTC, kamronbatman requested changes
Looks great, just some style nits!

2024-08-19 16:18 UTC, jefftaylor-okta commented
I just reviewed and these docs look awesome!

2024-08-19 16:35 UTC, kamronbatman approved these changes

2024-08-19 16:35 UTC, merged